spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/recipes_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    username: root
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
amazon:
  aws:
    access-key: ${AMAZON_ACCESS}
    secret-key: ${AMAZON_SECRET}
    region: eu-central-1
  s3:
    default-bucket: ${AMAZON_BUCKET_NAME}
jwt:
  secret: ${JWT_SECRET}